# Network
MODEL_USE: allForOne
NUM_TEAMS: 10
IMAGE_LINEAR_SIZE: 300
WORD_EMBED_SIZE: 300
HIDDEN_SIZE: 1024
FLAT_OUT_SIZE: 1024
USE_BBOX_FEAT: False

# Execution
USE_GLOVE: True
BATCH_SIZE: 32
LR_BASE: 0.0001
LR_DECAY_R: 0.2
LR_DECAY_LIST: [10, 12]
WARMUP_EPOCH: 3
MAX_EPOCH: 13
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 1
LOSS_FUNC: bce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
